// Export all animation components except the heavy ones we want to lazy load
export * from './aurora';
export * from './background-lines';
export * from './balatro';
export * from './beam-portal';
export * from './blob-background';
export * from './dither';
export * from './gradient-animation';
export * from './gradient-mesh';
export * from './grid-motion';
export * from './grid-pattern';
export * from './hyperspace-hero';
export * from './iridescence';
export * from './letter-glitch';
export * from './lightning';
export * from './liquid-chrome';
export * from './magnet-lines';
export * from './noise';
export * from './rain-drops';
export * from './shooting-stars';
export * from './sparkles';
export * from './sphere-animation';
export * from './spotlight';
export * from './squares';
export * from './starfall';
export * from './starry-background';
export * from './stars-background';
export * from './swarm-effect';
export * from './threads';
export * from './waves';
export * from './wavy-background';
export * from './world-map';

// Export only the types for the heavy components that will be lazy loaded
export type { AuroraBackgroundProps } from './aurora-background';
export type { AuroraCanvasProps } from './aurora-canvas';
export type { BackgroundBeamsProps } from './background-beams';
export type { BackgroundBoxesProps } from './background-boxes';
export type { BallpitProps } from './ballpit';
export type { CosmicSceneProps } from './cosmic-scene';
export type { GlobeConfig, GlobePosition, WorldProps as GlobeProps } from './globe';
export type { GridDistortionProps } from './grid-distortion';
export type { HyperspeedProps } from './hyperspeed';
export type { MeshMatrixProps } from './mesh-matrix';
export type { MeteorsProps } from './meteors';
export type { ParticleNetworkProps } from './particle-network';
export type { ParticleVeilProps } from './particle-veil';
export type { ParticlesProps } from './particles';
export type { VortexProps } from './vortex';
